Vagrant.configure(2) do |config|
	
	# Allows the virtual machine to use 2 CPU cores and 1 GB of memory
	config.vm.provider "virtualbox" do |v|
		v.cpus = 2
		v.memory = 512
	end
	
	# Use Debian Jessie 64 bit build
	config.vm.box = "debian/jessie64"
	
	config.vm.define "s01" do |s01|		
		s01.vm.network "private_network", ip: "192.168.0.11"
		
		s01.vm.hostname = "server01"
		
		s01.vm.synced_folder ".", "/vagrant", disabled: true
		
		s01.vm.provision "shell" do |shell|
			shell.path = "shell/setup.sh"
		end
	end
	
	config.vm.define "s02" do |s02|
		s02.vm.network "private_network", ip: "192.168.0.12"
		
		s02.vm.hostname = "server02"
		
		s02.vm.synced_folder ".", "/vagrant", disabled: true
		
		s02.vm.provision "shell" do |shell|
			shell.path = "shell/setup.sh"
		end
	end
	
	config.vm.define "s03" do |s03|
		s03.vm.network "private_network", ip: "192.168.0.13"
		
		s03.vm.hostname = "server03"
		
		s03.vm.synced_folder ".", "/vagrant", disabled: true
		
		s03.vm.provision "shell" do |shell|
			shell.path = "shell/setup.sh"
		end
	end
	
	config.vm.define "lb" do |lb|
		lb.vm.network "private_network", ip: "192.168.0.10"
		lb.vm.network "forwarded_port", guest: 80, host: 80
		
		lb.vm.hostname = "lb.haproxy"
		
		lb.vm.synced_folder ".", "/vagrant", disabled: true
		
		lb.vm.provision "shell" do |shell|
			shell.path = "shell/setup_ha.sh"
		end
	end
end